version: "3.8"

networks:
  rai_tester_network:
    driver: bridge

services:
  rai_service_tester_1:
    image: rai-service-tester:minimized
    volumes:
      - ./config.yml:/usr/app/config.yml
      - ./ready:/usr/app/ready
      - ./response_payload_1:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester --servertest' # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_1
      - RUST_LOG=info
      - PORT=7121
      - STATSD_HOST=graphite
    ports:
      - "7121:7121"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7121/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_2:
    image: rai-service-tester:minimized
    volumes:
      - ./config.yml:/usr/app/config.yml
      - ./ready:/usr/app/ready
      - ./response_payload_1:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester --servertest' # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_2
      - RUST_LOG=info
      - PORT=7122
      - STATSD_HOST=graphite
    ports:
      - "7122:7122"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7122/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_3:
    image: rai-service-tester:minimized
    volumes:
      - ./config.yml:/usr/app/config.yml
      - ./ready:/usr/app/ready
      - ./response_payload_1:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester --servertest' # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_3
      - RUST_LOG=info
      - PORT=7123
      - STATSD_HOST=graphite
    ports:
      - "7123:7123"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7123/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_4:
    image: rai-service-tester:minimized
    volumes:
      - ./config.yml:/usr/app/config.yml
      - ./ready:/usr/app/ready
      - ./response_payload_1:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester --servertest' # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_4
      - RUST_LOG=info
      - PORT=7124
      - STATSD_HOST=graphite
    ports:
      - "7124:7124"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7124/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_5:
    image: rai-service-tester:minimized
    volumes:
      - ./config.yml:/usr/app/config.yml
      - ./ready:/usr/app/ready
      - ./response_payload_1:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester --servertest' # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_5
      - RUST_LOG=info
      - PORT=7125
      - STATSD_HOST=graphite
    ports:
      - "7125:7125"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7125/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_iter:
    image: rai-service-tester-iter:minimized
    volumes:
      - ./config_iter.yml:/usr/app/config_iter.yml
      - ./ready:/usr/app/ready
      - ./response_payload:/usr/app/response_payload
    working_dir: /usr/app
    command: sh -c 'rm -rf /usr/app/response_payload/loadtest-response/* && /usr/app/rai-service-tester-iter'  # Perbaikan: Path executable
    environment:
      - SERVICE_NAME=rai_service_tester_iter
      - RUST_LOG=info
      - PORT=3030
      - STATSD_HOST=graphite
    ports:
      - "3030:3030"
    depends_on:
      - rai_service_tester_1
      - rai_service_tester_2
      - rai_service_tester_3
      - rai_service_tester_4
      - rai_service_tester_5
    networks:
      - rai_tester_network

  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - ./graphite_data:/opt/graphite/storage
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - rai_tester_network

  grafana:
    image: grafana/grafana-oss
    user: "104"  # Tambahkan user ID
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_plugins:/var/lib/grafana/plugins # Mount direktori plugins
    ports:
      - "3000:3000"
    networks:
      - rai_tester_network