version: '3.8'

networks:
  rai_tester_network:
    driver: bridge

services:
  rai_service_tester_1:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_1:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_1
      - RUST_LOG=info
      - PORT=7121
      - STATSD_HOST=graphite
    ports:
      - "7121:7121"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7121/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_2:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_2:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_2
      - RUST_LOG=info
      - PORT=7122
      - STATSD_HOST=graphite
    ports:
      - "7122:7122"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7122/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_3:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_3:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_3
      - RUST_LOG=info
      - PORT=7123
      - STATSD_HOST=graphite
    ports:
      - "7123:7123"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7123/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_4:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_4:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_4
      - RUST_LOG=info
      - PORT=7124
      - STATSD_HOST=graphite
    ports:
      - "7124:7124"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7124/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_5:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_5:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_5
      - RUST_LOG=info
      - PORT=7125
      - STATSD_HOST=graphite
    ports:
      - "7125:7125"
    depends_on:
      - graphite
      - grafana
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7125/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rai_tester_network

  rai_service_tester_iter:
    image: rai-service-tester-iter:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester-iter --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_iter
      - RUST_LOG=info
      - PORT=3030
      - STATSD_HOST=graphite
    ports:
      - "3030:3030"
    depends_on:
      rai_service_tester_1:
        condition: service_healthy
      rai_service_tester_2:
        condition: service_healthy
      rai_service_tester_3:
        condition: service_healthy
      rai_service_tester_4:
        condition: service_healthy
      rai_service_tester_5:
        condition: service_healthy
    networks:
      - rai_tester_network

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - rai_tester_network

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    networks:
      - rai_tester_network