version: '3.8'

services:
  rai_service_tester_1:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_1:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_1
      - RUST_LOG=info
      - PORT=7121
    ports:
      - "7121:7121"
    depends_on:
      - graphite
      - grafana

  rai_service_tester_2:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_2:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_2
      - RUST_LOG=info
      - PORT=7122
    ports:
      - "7122:7122"
    depends_on:
      - graphite
      - grafana

  rai_service_tester_3:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_3:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_3
      - RUST_LOG=info
      - PORT=7123
    ports:
      - "7123:7123"
    depends_on:
      - graphite
      - grafana

  rai_service_tester_4:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_4:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_4
      - RUST_LOG=info
      - PORT=7124
    ports:
      - "7124:7124"
    depends_on:
      - graphite
      - grafana

  rai_service_tester_5:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload_5:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_5
      - RUST_LOG=info
      - PORT=7125
    ports:
      - "7125:7125"
    depends_on:
      - graphite
      - grafana

  rai_service_tester_iter:
    image: rai-service-tester:latest
    volumes:
      - .:/usr/src/rai-service-tester-volume
      - ./config.yml:/usr/src/rai-service-tester/config.yml
      - ./ready:/usr/src/rai-service-tester/ready
      - ./response_payload:/usr/src/rai-service-tester/response_payload
    working_dir: /usr/src/rai-service-tester
    command: sh -c 'rm -rf /usr/src/rai-service-tester/response_payload/loadtest-response/* && /usr/src/rai-service-tester/target/release/rai-service-tester-iter --servertest'
    environment:
      - SERVICE_NAME=rai_service_tester_iter
      - RUST_LOG=info
      - PORT=3030
    ports:
      - "3030:3030"
    depends_on:
      - rai_service_tester_1
      - rai_service_tester_2
      - rai_service_tester_3
      - rai_service_tester_4
      - rai_service_tester_5

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"